"""empty message

Revision ID: 926b60cc7894
Revises: 41b9eb8c6f8f
Create Date: 2020-03-02 17:33:29.411326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926b60cc7894'
down_revision = '41b9eb8c6f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paydate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('payment')
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
